<?php

use CRM_Jobads_ExtensionUtil as E;

return [
    [
      'name' => 'OptionGroup_job_ads_role_description',
      'entity' => 'OptionGroup',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'name' => 'job_ads_role_description',
          'title' => E::ts('job ads role description'),
          'description' => NULL,
          'data_type' => 'String',
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'is_locked' => FALSE,
          'option_value_fields' => [
            'name',
            'label',
            'description',
          ],
        ],
        'match' => [
          'name',
        ],
      ],
    ],
    [
      'name' => 'OptionGroup_job_ads_role_description_OptionValue_Chief_Executive_Director',
      'entity' => 'OptionValue',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'option_group_id.name' => 'job_ads_role_description',
          'label' => E::ts('Chief Executive/Director'),
          'value' => '1',
          'name' => 'Chief Executive/Director',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        'match' => [
          'name',
          'option_group_id',
        ],
      ],
    ],
    [
      'name' => 'OptionGroup_job_ads_role_description_OptionValue_Manager',
      'entity' => 'OptionValue',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'option_group_id.name' => 'job_ads_role_description',
          'label' => E::ts('Manager'),
          'value' => '2',
          'name' => 'Manager',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        'match' => [
          'name',
          'option_group_id',
        ],
      ],
    ],
    [
      'name' => 'OptionGroup_job_ads_role_description_OptionValue_Coordinator',
      'entity' => 'OptionValue',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'option_group_id.name' => 'job_ads_role_description',
          'label' => E::ts('Coordinator'),
          'value' => '3',
          'name' => 'Coordinator',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        'match' => [
          'name',
          'option_group_id',
        ],
      ],
    ],
    [
      'name' => 'OptionGroup_job_ads_role_description_OptionValue_Officer',
      'entity' => 'OptionValue',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'option_group_id.name' => 'job_ads_role_description',
          'label' => E::ts('Officer'),
          'value' => '4',
          'name' => 'Officer',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        'match' => [
          'name',
          'option_group_id',
        ],
      ],
    ],
    [
      'name' => 'OptionGroup_job_ads_role_description_OptionValue_Senior_Project_Support',
      'entity' => 'OptionValue',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'option_group_id.name' => 'job_ads_role_description',
          'label' => E::ts('Senior Project Support'),
          'value' => '5',
          'name' => 'Senior Project Support',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        'match' => [
          'name',
          'option_group_id',
        ],
      ],
    ],
    [
      'name' => 'OptionGroup_job_ads_role_description_OptionValue_Project_Support',
      'entity' => 'OptionValue',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'option_group_id.name' => 'job_ads_role_description',
          'label' => E::ts('Project Support'),
          'value' => '6',
          'name' => 'Project Support',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        'match' => [
          'name',
          'option_group_id',
        ],
      ],
    ],
    [
      'name' => 'OptionGroup_job_ads_role_description_OptionValue_Finance',
      'entity' => 'OptionValue',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'option_group_id.name' => 'job_ads_role_description',
          'label' => E::ts('Finance'),
          'value' => '7',
          'name' => 'Finance',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        'match' => [
          'name',
          'option_group_id',
        ],
      ],
    ],
    [
      'name' => 'OptionGroup_job_ads_role_description_OptionValue_Administration',
      'entity' => 'OptionValue',
      'cleanup' => 'unused',
      'update' => 'unmodified',
      'params' => [
        'version' => 4,
        'values' => [
          'option_group_id.name' => 'job_ads_role_description',
          'label' => E::ts('Administration'),
          'value' => '8',
          'name' => 'Administration',
          'grouping' => NULL,
          'filter' => 0,
          'is_default' => FALSE,
          'description' => NULL,
          'is_optgroup' => FALSE,
          'is_reserved' => FALSE,
          'is_active' => TRUE,
          'component_id' => NULL,
          'domain_id' => NULL,
          'visibility_id' => NULL,
          'icon' => NULL,
          'color' => NULL,
        ],
        'match' => [
          'name',
          'option_group_id',
        ],
      ],
    ],
  ];