-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_job_ad`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_job_ad
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_job_ad` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique JobAd ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `job_title` varchar(255) NOT NULL COMMENT 'Job title',
  `summary` longtext COMMENT 'Short summary to go in the main listing',
  `description` longtext COMMENT 'Full description',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_job_ad_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
