-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_job_ad`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_job_ad
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_job_ad` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique JobAd ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `organisation_name` varchar(255) NOT NULL COMMENT 'Name of organisation for the role - could be different from organisation posting the role',
  `job_title` varchar(255) NOT NULL COMMENT 'Job title',
  `description` longtext COMMENT 'Full description',
  `application_deadline` datetime NOT NULL,
  `website` longtext,
  `fixed_salary` decimal(20,2) COMMENT 'Fixed salary',
  `salary_from` decimal(20,2) COMMENT 'Salary from (£)',
  `salary_to` decimal(20,2) COMMENT 'Salary to (£)',
  `contract_type` int unsigned NOT NULL DEFAULT 1 COMMENT 'valid value, registered contract type',
  `full_or_part_time` int unsigned NOT NULL DEFAULT 1 COMMENT 'valid value from Full or Part time option group',
  `salary_rate` int unsigned NOT NULL DEFAULT 1 COMMENT 'valid value from Salary Rate option group',
  `salary_scale` int unsigned NOT NULL DEFAULT 1 COMMENT 'valid value from Salary Scale option group',
  `salary_type` int unsigned NOT NULL DEFAULT 1 COMMENT 'valid value from Salary Type option group',
  `role_description` int unsigned NOT NULL DEFAULT 1 COMMENT 'valid value from Role description option group',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_job_ad_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
